### ISSUE TITLE
Can we rename this project "nodeclipse-1" to "nodeclipse"?

### ISSUE THREAD

**Issue by lamb** [Nodeclipse/nodeclipse-1#208]
Can we rename this project "nodeclipse-1" to "nodeclipse"?
So many people ask me why "xxxxx-1", I can not answer why.

**Comment by paulvi** [comment]
There answer is because there has been https://github.com/Nodeclipse/nodeclipse

and nodeclipse-1 was fork made by @tomotaro1065 Tomoyuki

See https://github.com/Nodeclipse/nodeclipse-1/#personal-message

We should add more about first commit at www.nodeclipse.org and README

I'd like to have fork history preserved. Even Node.jx 4.x is actually fork, but now they don't want to mention that https://github.com/nodejs/node/pull/3001

**Comment by paulvi** [comment]
Also too many places already  where https://github.com/Nodeclipse/nodeclipse-1 is given as link
